version = 3
final_space = true

[palette]
  blue = '#8AADF4'
  closer = 'p:os'
  lavender = '#B7BDF8'
  os = '#ACB0BE'
  pink = '#F5BDE6'

[transient_prompt]
  template = ''
  foreground = 'p:closer'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{.Icon}} '
    foreground = 'p:os'
    type = 'os'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'p:pink'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      folder_icon = ''
      home_icon = ''
      max_width = 30
      style = 'powerlevel'

      [blocks.segments.properties.mapped_locations]
        '~/.config' = ''
        '~/Program' = ''

  [[blocks.segments]]
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
    foreground = 'p:lavender'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ''
    foreground = 'p:closer'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#FF5252{{ end }}']

    [blocks.segments.properties]
      cache_duration = 'none'
